# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Mater"
license = "MIT"
#licenselink = "https://github.com/nofw/nofw.io/blob/master/LICENSE"
description = "Material Hugo theme based on Materialize CSS"
#homepage = "https://nofw.io"
tags = []
features = []
min_version = "0.20"

[author]
    name = "Márk Sági-Kazár"
    homepage = "https://sagikazarmark.hu"
